<table>
  <tr>
    <td colspan="2"><strong>Заголовок</strong></td>
  </tr>
  <tr>
    <td>%%name.title%%</td>
    <td>%%name.value%%</td>
  </tr>
  <tr>
    <td>%%tell.title%%</td>
    <td>%%tell.value%%</td>
  </tr>
  <tr>
    <td>%%e-mail.title%%</td>
    <td>%%e-mail.value%%</td>
  </tr>
  <tr>
    <td>%%text.title%%</td>
    <td>%%text.value%%</td>
  </tr>
  <tr>
    <td>%%checkbox.title%%</td>
    <td>%%checkbox.value%%</td>
  </tr>
</table>
